<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    /**
     * Create and sign in a user
     *
     * @param array|null $options
     *
     * @return $this
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

//        $this->withoutExceptionHandling();
    }

    public function signIn($user = null)
    {
        $user = $user ?: \App\Models\User::factory()->create(['email_verified_at' => now()->toString()]);
        return $this->actingAs($user);
    }
}
