<?php

namespace Tests\Unit;

use Illuminate\Foundation\Testing\RefreshDatabase;
use PHPUnit\Framework\TestCase;
use App\Models\Course;

class CourseTest extends TestCase
{
    use RefreshDatabase;

    protected Course $course;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    public function test_course_has_a_path(){

    }
}
